export const countries = [
  ['Saudi Arabia', '+966', 'SA'],
  ['UAE', '+971', 'AE'],
  ['Qatar', '+974', 'QA'],
  ['Kuwait', '+965', 'KW'],
  ['Bahrain', '+973', 'BH'],
  ['Oman', '+968', 'OM'],
  ['Egypt', '+20', 'EG'],
  ['Jordan', '+962', 'JO'],
  ['Lebanon', '+961', 'LB'],
  ['United Kingdom', '+44', 'GB'],
  ['United States', '+1', 'US'],
  ['Germany', '+49', 'DE'],
  ['France', '+33', 'FR'],
  ['India', '+91', 'IN'],
  ['Pakistan', '+92', 'PK'],
  ['Turkey', '+90', 'TR'],
];
